// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABWiouCl5ScDbl1pUKLMYlIy6yWRdQOJ0',
    appId: '1:429297447925:web:5fb713988d68e584dea6bc',
    messagingSenderId: '429297447925',
    projectId: 'basketball-scorebook-8e490',
    authDomain: 'basketball-scorebook-8e490.firebaseapp.com',
    storageBucket: 'basketball-scorebook-8e490.firebasestorage.app',
    measurementId: 'G-KV4T7PW6C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqoFoU5_Jo6vL5lSXzvLBRUK70Vtefvi0',
    appId: '1:429297447925:android:ddd124d3dc95fd65dea6bc',
    messagingSenderId: '429297447925',
    projectId: 'basketball-scorebook-8e490',
    storageBucket: 'basketball-scorebook-8e490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH2cpjnncl2X1flq1zSAYhTp8ov_ftZO0',
    appId: '1:429297447925:ios:9b237b895458b4d3dea6bc',
    messagingSenderId: '429297447925',
    projectId: 'basketball-scorebook-8e490',
    storageBucket: 'basketball-scorebook-8e490.firebasestorage.app',
    iosBundleId: 'com.example.basketballScorebook',
  );
}
